#!/bin/bash
# Copyright (C) 2010  Serge V. Baumer

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Output XML Encoding map for Expat from unicode.org mapping table
# usage: ./xmlencmap encname filepath [,]
# 	encname    encoding name
#	filepath   mapping file path inside http://unicode.org/Public/MAPPINGS/
#	,          put it (comma) at very end of output

urlbase='http://unicode.org/Public/MAPPINGS/'
encname=$1
filepath=$2
comma=$3
wget -O - 'http://unicode.org/Public/MAPPINGS/'${filepath} 2>/dev/null |
awk '
BEGIN { 
	printf "{\"'$encname'\", {"
	counter = -1
}
/^0x/ {
	code = strtonum($1)
	counter++
	/*print " ", code, " ", counter*/
	while (code > counter) {
		printf "%d", -1 
		counter++
		if (counter != 255)
			printf ", "
	}
	if ($2 == "#UNDEFINED")
		printf "%d", -1
	else
		printf "%s", $2
	if (counter != 255)
		printf ", "
}
END {
		printf "}}'$comma'\n"
}'
